coverage:
  range: 60..85 # test coverage thresholds. 60% and below fails (red), 85% and up passes (green), between is "yellow"
  round: down
  precision: 1
  status:
    project:
      default:
        target: 85% # require new commits to have at least 85% coverage
        threshold: 2% # more than 2% coverage drop, fail.
    patch:
      default:
        enabled: no
ignore:
  - "**/SystemConsole.cs" # an abstraction for testability of System.Console. Cannot be tested headless.
